version: '2.4'
services:
  us-server: 
    image: "docker.io/library/local_allq_server"
    init: true
    ports:
      - 7788:7788
    networks:
      - test-foo
    environment:
      - SERVER_PORT=7788
      - ALLQ_DEBUG=true
      - A_CURVE_SECRETKEY=SkgmWig0MzpHclo0dSoxSXZyeUsta05IbV1eKk1mW2liYy1kNlFGOAA=
      - A_CURVE_PUBLICKEY=N21kJChibWV6TCsjLTNWdTp2Wj5INzJWdDQ1NVAoREhAYyZRIyFIagA=
  us_queue:
    image: "docker.io/library/local_allq_client"
    init: true
    oom_kill_disable: true
    networks:
      - test-foo
    environment:
      - SERVER_STRING=us-server:7788
      - MULTIPROCESS=true
      - A_CURVE_PUBLICKEY=WyVIWUN5KS8yXUJyLlRCfTMqRjplMDd2IS5LQiQlaiY6ekJZVS1SawA=
      - A_CURVE_SECRETKEY=NCQvdGJ3cHl1ZihjIzlpYmdeXShIdClnOmpNSns1Ni5pJWliSmVSMAA=
      - A_CURVE_SERVER_PUBLICKEY=N21kJChibWV6TCsjLTNWdTp2Wj5INzJWdDQ1NVAoREhAYyZRIyFIagA=
      - TCP_CLIENT_PORT=7768
      - ALLQ_DEBUG=true
    ports:
      - 7768:7768
      - 8090:8090
    restart: unless-stopped

networks:
  test-foo:
