version: '2.4'
services:
  us-server: 
    image: "docker.io/library/local_allq_server"
    init: true
    ports:
      - 7788:7788
    networks:
      - test-foo
    environment:
      - SERVER_PORT=7788
      - ALLQ_DEBUG=true
      - A_CURVE_PUBLICKEY=SF59dncubHJiT0xGZn1jK1B1dzZIbTNVOjBOJW12a0VrZTBsdT40KwA=
      - A_CURVE_SECRETKEY=OnBALzBOKjxpW21SbEYqNXdkNG1IXVlvd1FYZyV9YjZzejhUcjVpaAA=
  us_queue:
    image: "docker.io/library/local_allq_client"
    init: true
    oom_kill_disable: true
    networks:
      - test-foo
    environment:
      - SERVER_STRING=us-server:7788
      - MULTIPROCESS=true
      -  A_CURVE_PUBLICKEY=QT5KKUdTdXFbTzZmSWQ8VzUxST1vNEVISFV9ZF5kdSlYLiUoR2FTPwA=
      -  A_CURVE_SECRETKEY=YXEjKSs+R1pvTFZGVlBXd2xwMkpsdiohfVhmLUJ6KUs/d0V3ZGYqSQA=
      -  A_CURVE_SERVER_PUBLICKEY=SF59dncubHJiT0xGZn1jK1B1dzZIbTNVOjBOJW12a0VrZTBsdT40KwA=
      - TCP_CLIENT_PORT=7768
      - ALLQ_DEBUG=true
    ports:
      - 7768:7768
      - 8090:8090
    restart: unless-stopped

networks:
  test-foo:


