=begin
#AllQ

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Allq::AdminApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AdminApi' do
  before do
    # run before each test
    @instance = Allq::AdminApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdminApi' do
    it 'should create an instance of AdminApi' do
      expect(@instance).to be_instance_of(Allq::AdminApi)
    end
  end

  # unit tests for stats_get
  # Stats
  # Get Stats
  # @param [Hash] opts the optional parameters
  # @return [Array<StatsResults>]
  describe 'stats_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_servers_put
  # Reset Server Urls
  # Change server URLs
  # @param server_urls Comma Separated List URL String
  # @param [Hash] opts the optional parameters
  # @return [BasicResponse]
  describe 'update_servers_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
