require 'spec_helper'
require 'json'

def restart_server
  puts `docker restart docker-allq-server`
end

DEFAULT_TUBE = "default"
ALT_TUBE = ""
# Unit tests for Allq::ActionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RestartAPITests' do
  before do
    # run before each test
    @instance = Allq::ActionsApi.new
    stats_result = AllQTools::get_stats[0]
    stats_result.stats.each do |stat|
      puts stat.inspect
      @instance.tube_delete(stat.tube)
    end
  end

  after do
    # run after each test
  end

  # unit tests for bury_put
  # Bury
  # Bury Job
  # @param job_id Job ID
  # @param [Hash] opts the optional parameters
  # @return [BasicResponse]
  describe 'should reload ready test' do
    it "should work" do
      AllQTools::add_job
      expect(AllQTools::get_ready(DEFAULT_TUBE)).to eq(1)
      restart_server
      expect(AllQTools::get_ready(DEFAULT_TUBE)).to eq(1)      
    end
  end

  # unit tests for job_delete
  # Delete
  # Finished Job
  # @param job_id Job ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tube Name of Tube (For deleting \&quot;ready\&quot; objects)
  # @return [BasicResponse]
  # describe 'job_delete test' do
  #   it "should work" do
  #     AllQTools::add_job
  #     expect(AllQTools::get_ready(DEFAULT_TUBE)).to eq(1)
  #     job = @instance.peek_get(DEFAULT_TUBE)
  #     @instance.job_delete(job.id, tube: DEFAULT_TUBE)
  #     expect(AllQTools::get_ready(DEFAULT_TUBE)).to eq(0)
  #   end
  # end
end


